# Base configs
baseurl: "http://ps.efe61.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-106757701-1"

# UI configs
title: "Photoshop by Mehmet Efe Karadeniz"
subtitle: "Be amazed by my masterpieces."
author: "Mehmet Efe Karadeniz"
bio: "I am a high school student at UAA. I am currently learning Photoshop, Final Cut Pro and some Android coding."
#publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://twitter.com/MehmetEfeKarad_"
  instagram: "https://www.instagram.com/mehmetefekaradeniz"
  #dribbble: "https://dribbble.com/ramswaroop"
  #linkedin: "https://in.linkedin.com/in/ramswarooppatra"
  github: "https://www.github.com/mehmet-efe61"
